language: node_js

services:
  - docker

node_js:
  - "8"

branches:
  only:
    - master

install:
  - yarn install

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - yarn validate
        - npm run semantic-release